### ISSUE TITLE
Find a way to keep secrets outside the repo and easily available in production

### ISSUE THREAD

**Issue by Nagasaki45** [Nagasaki45/Xteams#18]
For example: email configuration, for admin mails, or telegram bot token

**Comment by nonZero** [comment]
See parseaddr or getaddresses
https://docs.python.org/3/library/email.util.html#email.utils.parseaddr

**Comment by Nagasaki45** [comment]
Hi @nonZero,

The issue here is how to keep "secrets" outside the repo and still have them available in production without too much manual configuration.
I'm in the middle of the migration from heroku to my own server (on digital ocean) and most of the recent work (and open tickets) are associated with this change.
Maybe I need to add a label of "deployment" to this (and many other) tickets.

Anyway, I'm happy to see that you are watching this repo and thanks for the input!

**Comment by nonZero** [comment]
Personally I like keeping a host based local_settings file for these kind
of things.

**Comment by Nagasaki45** [comment]
I'm using docker-compose in production (the README explains most of the configuration). With your suggestion I need this file be in the repo dir before building the docker image and maintain it state somehow. I sure that there are tools for this, I just have figure it out.
