### ISSUE TITLE
Add bots to create teams using telegram / whatsapp

### ISSUE THREAD

**Issue by Nagasaki45** [Nagasaki45/Xteams#19]
Have a /list command to see all of the players on the court; /in <NAME>, /out <NAME>, and /bench <NAME> to move a player between lists and /teams command to generate teams.
There should be also a /setgroup <GROUP_NAME> to associate the chat with an Xteams group.

**Comment by nonZero** [comment]
AFAIK whatsapp is a closed platform.  Bots will always be considered as a
bad hack.
Telegram seems to have a decent API.
email is also cool

**Comment by Nagasaki45** [comment]
@nonZero, you are right. I'm currently working on developing a telegram bot with https://github.com/eternnoir/pyTelegramBotAPI, which looks pretty straightforward. You can watch my progress in the "bot" branch (it is a temporary branch. I'm "backuping" work to github, a bad habit...).

I wish I could develop a whatsapp bot too, as our volleyball group uses whatsapp extensively.

**Comment by Nagasaki45** [comment]
Won't happen. Closing.
