### ISSUE TITLE
Modify gunicorn flags to production

### ISSUE THREAD

**Issue by Nagasaki45** [Nagasaki45/Xteams#53]

**Comment by nonZero** [comment]
--workers
--name (+ add setproctitle to requirements)
--pid (for reload)

**Comment by Nagasaki45** [comment]
@nonZero, thanks!
I will only add `--workers` for now. When I will start to work on no downtime deployments (issue #54) I will add one more web container, load balance between them using the system wide Nginx, and improve my deployment fabfile to take them down and up one by one.
