### ISSUE TITLE
grouping in education

### ISSUE THREAD

**Issue by lotan1** [Nagasaki45/Xteams#55]
what about using your methods to create groups in classrooms?
or even to help random people to act together for common goal?
I was oriented here with the good help of udi oron, when asking him about something I am working on, 
Please take a look https://app.emaze.com/@AFTLWOLO/-022?fullscreen&redaolon , and I would like to hear your saying

**Comment by Nagasaki45** [comment]
Hi @lotan1,
You project seems very interesting!
In Xteams, creation of groups is done using a very simple optimization algorithm:
1. A set of players is given, each one with a single numerical score.
2. The players are partitioned to groups of the same size randomly.
3. The score of each group is calculated as the sum of the players score.
4. Steps 2 and 3 are repeated several times, providing several possible partitions of the players.
5. From all of the possible partitions I choose the one that have the minimal score variance between the groups.

If you are attempting to follow a similar approach you will have to decide about a target function to minimize. For me, it was the variance of the group scores.

Feel free to take and modify `groups/grouper.py` module. All the logic is there.
